### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by gmangesh** [AbeEstrada/atom-format-sql#5]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:53:11)
Object.activate (/Users/gmangesh/.atom/packages/format-sql/lib/format-sql.coffee:5:9)
```

**Comment by vietarmis** [comment]
I sent a pull request for this.

**Comment by AbeEstrada** [comment]
Fixed in https://github.com/AbeEstrada/atom-format-sql/commit/bdd5c74a87bcaef679e94a73ebd358614a5ec70e

Thanks.
