### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by f0nziePT** [AbeEstrada/atom-format-sql#7]
Hi, just the first time i'm using this package and it didn't work :(

Can you help?

atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\fonseca.QUIDGEST\AppData\Local\atom\app-0.187.0\resources\app\src\atom.js:54:11)
Object.activate (C:\Users\fonseca.QUIDGEST\.atom\packages\format-sql\lib\format-sql.coffee:5:9)
```

**Comment by AbeEstrada** [comment]
Fixed on https://github.com/AbeEstrada/atom-format-sql/commit/7798e58d97af2f51a32833c57c5c8a26eb9155d1
